
services:
###> php service ###
  php:
    build:
      context: .
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    working_dir: /var/www
    command: php -S 0.0.0.0:8000 -t public
###< doctrine/doctrine-bundle ###
